//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.EventListSqmple
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class EventListSqmple { }
#else

	public class EventListSqmple : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public EventListSqmple()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/MyHero;component/SampleData/EventListSqmple/EventListSqmple.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _url_photo = string.Empty;

		public string url_photo
		{
			get
			{
				return this._url_photo;
			}

			set
			{
				if (this._url_photo != value)
				{
					this._url_photo = value;
					this.OnPropertyChanged("url_photo");
				}
			}
		}

		private string _text = string.Empty;

		public string text
		{
			get
			{
				return this._text;
			}

			set
			{
				if (this._text != value)
				{
					this._text = value;
					this.OnPropertyChanged("text");
				}
			}
		}

		private double _nb_plus = 0;

		public double nb_plus
		{
			get
			{
				return this._nb_plus;
			}

			set
			{
				if (this._nb_plus != value)
				{
					this._nb_plus = value;
					this.OnPropertyChanged("nb_plus");
				}
			}
		}

		private string _date = string.Empty;

		public string date
		{
			get
			{
				return this._date;
			}

			set
			{
				if (this._date != value)
				{
					this._date = value;
					this.OnPropertyChanged("date");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
